// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: hextech.proto

package hextech

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Broker_ProcessCommand_FullMethodName          = "/hextech.Broker/ProcessCommand"
	Broker_ObtenerProducto_FullMethodName         = "/hextech.Broker/ObtenerProducto"
	Broker_GetRandServer_FullMethodName           = "/hextech.Broker/GetRandServer"
	Broker_GetClock_FullMethodName                = "/hextech.Broker/GetClock"
	Broker_NotificarInconsistencia_FullMethodName = "/hextech.Broker/NotificarInconsistencia"
)

// BrokerClient is the client API for Broker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerClient interface {
	ProcessCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	ObtenerProducto(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	GetRandServer(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RandServerResponse, error)
	GetClock(ctx context.Context, in *ClockRequest, opts ...grpc.CallOption) (*ClockResponse, error)
	NotificarInconsistencia(ctx context.Context, in *InconsistenciaRequest, opts ...grpc.CallOption) (*InconsistenciaResponse, error)
}

type brokerClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerClient(cc grpc.ClientConnInterface) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) ProcessCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, Broker_ProcessCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) ObtenerProducto(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, Broker_ObtenerProducto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) GetRandServer(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RandServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RandServerResponse)
	err := c.cc.Invoke(ctx, Broker_GetRandServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) GetClock(ctx context.Context, in *ClockRequest, opts ...grpc.CallOption) (*ClockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClockResponse)
	err := c.cc.Invoke(ctx, Broker_GetClock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) NotificarInconsistencia(ctx context.Context, in *InconsistenciaRequest, opts ...grpc.CallOption) (*InconsistenciaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InconsistenciaResponse)
	err := c.cc.Invoke(ctx, Broker_NotificarInconsistencia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServer is the server API for Broker service.
// All implementations must embed UnimplementedBrokerServer
// for forward compatibility.
type BrokerServer interface {
	ProcessCommand(context.Context, *CommandRequest) (*CommandResponse, error)
	ObtenerProducto(context.Context, *CommandRequest) (*CommandResponse, error)
	GetRandServer(context.Context, *EmptyRequest) (*RandServerResponse, error)
	GetClock(context.Context, *ClockRequest) (*ClockResponse, error)
	NotificarInconsistencia(context.Context, *InconsistenciaRequest) (*InconsistenciaResponse, error)
	mustEmbedUnimplementedBrokerServer()
}

// UnimplementedBrokerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrokerServer struct{}

func (UnimplementedBrokerServer) ProcessCommand(context.Context, *CommandRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessCommand not implemented")
}
func (UnimplementedBrokerServer) ObtenerProducto(context.Context, *CommandRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerProducto not implemented")
}
func (UnimplementedBrokerServer) GetRandServer(context.Context, *EmptyRequest) (*RandServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandServer not implemented")
}
func (UnimplementedBrokerServer) GetClock(context.Context, *ClockRequest) (*ClockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClock not implemented")
}
func (UnimplementedBrokerServer) NotificarInconsistencia(context.Context, *InconsistenciaRequest) (*InconsistenciaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotificarInconsistencia not implemented")
}
func (UnimplementedBrokerServer) mustEmbedUnimplementedBrokerServer() {}
func (UnimplementedBrokerServer) testEmbeddedByValue()                {}

// UnsafeBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServer will
// result in compilation errors.
type UnsafeBrokerServer interface {
	mustEmbedUnimplementedBrokerServer()
}

func RegisterBrokerServer(s grpc.ServiceRegistrar, srv BrokerServer) {
	// If the following call pancis, it indicates UnimplementedBrokerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Broker_ServiceDesc, srv)
}

func _Broker_ProcessCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).ProcessCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_ProcessCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).ProcessCommand(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_ObtenerProducto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).ObtenerProducto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_ObtenerProducto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).ObtenerProducto(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_GetRandServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetRandServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_GetRandServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetRandServer(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_GetClock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetClock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_GetClock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetClock(ctx, req.(*ClockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_NotificarInconsistencia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InconsistenciaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).NotificarInconsistencia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_NotificarInconsistencia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).NotificarInconsistencia(ctx, req.(*InconsistenciaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Broker_ServiceDesc is the grpc.ServiceDesc for Broker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Broker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hextech.Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessCommand",
			Handler:    _Broker_ProcessCommand_Handler,
		},
		{
			MethodName: "ObtenerProducto",
			Handler:    _Broker_ObtenerProducto_Handler,
		},
		{
			MethodName: "GetRandServer",
			Handler:    _Broker_GetRandServer_Handler,
		},
		{
			MethodName: "GetClock",
			Handler:    _Broker_GetClock_Handler,
		},
		{
			MethodName: "NotificarInconsistencia",
			Handler:    _Broker_NotificarInconsistencia_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hextech.proto",
}
